#!/bin/sh
# File generated by ocamlbuild

cd /home/edouda/OCaml

rm -f binaryTree.cmi
rm -f binaryTree.cmo
rm -f exercises.cmi
rm -f exercises.cmo
rm -f main.cmi
rm -f main.cmo
rm -f rsa.cmi
rm -f rsa.cmo
# Also clean the script itself
rm -f /home/edouda/OCaml/_build/sanitize.sh
