run :
	gcc -Wall anagr.c -o anagrs
	./anagrs
all :
	gcc -Wall anagr.c -o anagrs
runml :
	ocamlc -w A anagr.ml -o anagrml
	./anagrml
allml :
	ocamlc -w A anagr.ml -o anagrml
runopt :
	ocamlopt -w A anagr.ml -o anagrml
